[workspace]
resolver = "2"
members = ["libs/ferrisquote-auth","libs/ferrisquote-domain", "libs/ferrisquote-postgres"]


[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["nathaelb <pro.nathaelbonnal@gmail.com>", "jorisvilardell <joris.vilardell@outlook.com>"]
license = "Apache-2.0"
