[workspace]
resolver = "2"
members = ["libs/ferrisquote-auth","libs/ferrisquote-domain", "libs/ferrisquote-postgres", "apps/api", "libs/ferrisquote-core"]


[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["nathaelb <pro.nathaelbonnal@gmail.com>"]
license = "Apache-2.0"
